### PR TITLE
pipeline: fix container lifecycle events

### LINKED ISSUE #1664: container_create and container_remove are not displayed with container filter on
Hi,

tracee-ebpf v0.7.0,  when running with container filter (-t container), container_create and container_remove events are filtered out. existing_container event works fine (does appear).

### PR DESCRIPTION
**Pull request by yanivagman**
## Initial Checklist

- [x] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

When using container mode, container_create and container_remove events
were not emitted. Fix this.

Fix #1664

## Type of change

- [x] Bug fix (non-breaking change fixing an issue, preferable).
- [ ] Quick fix (minor non-breaking change requiring no issue, use with care)
- [ ] Code refactor (code improvement and/or code removal)
- [ ] New feature (non-breaking change adding functionality).
- [ ] Breaking change (cause existing functionality not to work as expected).

## How Has This Been Tested?
Manually 

Tests being included in this PR:

- [ ] Test File A
- [ ] Test File B

Reproduce the test by running:

- command 01
- command 02

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [x] I have made corresponding changes to the documentation.
- [x] My code follows the style guidelines (C and Go) of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented all functions/methods created explaining what they do.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix, or feature, is effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [x] Subject starts with "subsystem|file: description".
- [x] Do not end the subject line with a period.
- [x] Limit the subject line to 50 characters.
- [x] Separate subject from body with a blank line.
- [x] Use the imperative mood in the subject line.
- [x] Wrap the body at 72 characters.
- [x] Use the body to explain what and why instead of how.

### CODE REVIEW

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

File: pkg/ebpf/events_pipeline.go [hunk 1]
```diff
@@ -243,8 +243,10 @@ func (t *Tracee) processEvents(ctx gocontext.Context, in <-chan *trace.Event) (<
 				// Although kernel filters shouldn't submit such events, we do this check to be on the safe side.
 				// For example, it might be that a new cgroup was created, and not by a container runtime,
 				// while we still didn't processed the cgroup_mkdir event and removed the cgroupid from the bpf container map.
-				// Note: this check should be placed after processEvent() so cgroup_mkdir event is processed
-				continue
+				id := events.ID(event.EventID)
+				if id != events.CgroupMkdir && id != events.CgroupRmdir {
```
Comment (NDStrahilevitz) [inline pkg/ebpf/events_pipeline.go:247]: Can you add a comment describing that this is derived into container_create and container_removed respectively? Wasn't obvious at a glance.

**Review by NDStrahilevitz — APPROVED** [review]
LGTM
