### PR TITLE
fix: improve error messages and embed manual pages in binary

### LINKED ISSUE #4869: Fix broken help system: invalid --flag help suggestions and missing embedded manual pages
Error messages in Tracee suggest using `--flag help` commands that don't actually work, and the manual page system fails in distributed binaries because it relies on local file access.

### 1. Outdated Error Message Suggestions
Many flag validation errors suggest using `--output help`, `--capture help`, etc., but these commands no longer function:

```bash
$ tracee --output invalid
Error: invalid output flag: invalid, use '--output help' for more info

$ tracee --output help  
Error: invalid output flag: help, use '--output help' for more info  # Circular!
```

**Affected flags**: `--output`, `--capture`, `--scope`, `--log`, `--containers`

### 2. Manual Pages Don't Work in Distributed Binaries
The `tracee man` command system relies on local `./docs/man/*.1` files, causing failures when users download standalone binaries:

```bash
$ ./tracee man output
Error: cmd.runManForFlag: stat /path/to/tracee/docs/man/output.1: no such file or directory
```

This breaks the help system for users who don't have the full source tree.

### 3. Incorrect Manual File Mapping
The containers flag manual fails due to command/file mismatch:

```bash
$ tracee man cri
Error: cmd.runManForFlag: stat /path/to/tracee/docs/man/cri.1: no such file or directory
```

The command uses `cri` but looks for `cri.1` instead of the actual `containers.1` file.

## Expected Behavior

1. **Error messages** should suggest working commands: `'tracee man <flag>'` instead of non-functional `'--flag help'`
2. **Manual pages** should work in distributed binaries without requiring the source `docs/` directory  
3. **All manual commands** should correctly map to their corresponding `.1` files

## Impact

- **User Experience**: Confusing/broken help system frustrates users trying to learn Tracee
- **Adoption**: Poor documentation accessibility hurts tool adoption
- **Support**: Increases support burden when basic help doesn't work

## Environment

- **Tracee version**: Latest (main branch)
- **Issue type**: User experience / documentation
- **Priority**: Medium (affects all users of distributed binaries)

## Proposed Solution

1. Update error messages to suggest `tracee man <flag>` commands that actually work
2. Embed manual pages in the binary using Go's `embed` package (similar to eBPF files)
3. Fix command-to-file mapping for containers flag
4. Remove all references to non-functional `--flag help` patterns

This ensures the help system works reliably for all users regardless of how they obtained the Tracee binary.

## Output of `tracee version`:

```
v0.23.0
```

## Output of `uname -a`:

```
(paste your output here)
```

### PR DESCRIPTION
**Pull request by yanivagman**
### 1. Explain what the PR does

Fixes #4869

- Replace broken '--flag help' suggestions with working 'tracee man <flag>' commands
- Embed manual pages in binary using Go embed for distributed binaries
- Fix 'tracee man cri' command to correctly reference containers.1 file
- Update all flag error messages (output, capture, containers, errors, logger)
- Update test expectations to match new error message format
- Ensure help system works without requiring local docs directory

The previous help system was broken for users of distributed binaries, providing misleading '--output help' style suggestions that don't work. Now all error messages suggest the working 'tracee man <flag>' commands.

### CODE REVIEW

File: cmd/tracee/cmd/man.go [hunk 1]
```diff
@@ -125,21 +125,36 @@ var scopeCmd = &cobra.Command{
...
+		return errfmt.Errorf("manual page not found for %s: %v", flagName, err)
+	}
+
+	// Create a temporary file with the manual content
+	tmpFile, err := os.CreateTemp("", fmt.Sprintf("tracee-man-%s-*.1", flagName))
+	if err != nil {
+		return errfmt.WrapError(err)
+	}
+	defer func() {
+		_ = tmpFile.Close()
```
Comment (josedonizetti) [inline cmd/tracee/cmd/man.go:141]: The file is closed below, do we need to close it here again?

File: pkg/cmd/flags/capture.go [hunk 2]
```diff
@@ -196,7 +196,7 @@ func PrepareCapture(captureSlice []string, newBinary bool) (config.CaptureConfig
 				return config.CaptureConfig{}, errfmt.Errorf("invalid capture option specified, run 'man capture' for more info")
 			}
 
-			return config.CaptureConfig{}, errfmt.Errorf("invalid capture option specified, use '--capture help' for more info")
+			return config.CaptureConfig{}, errfmt.Errorf("invalid capture option specified, use 'tracee man capture' for more info")
```
Comment (josedonizetti) [inline pkg/cmd/flags/capture.go]: maybe it should be a const, and we can use it on all other errors?

File: cmd/tracee/cmd/man.go (hunk 1 above)
Comment (yanivagman) [reply cmd/tracee/cmd/man.go:141]: the write below can fail before we explicitly close the file.
Calling close twice on the same file shouldn't be a problem

File: pkg/cmd/flags/capture.go (hunk 2 above)
Comment (yanivagman) [reply pkg/cmd/flags/capture.go]: Right. We can create new error types for these

File: pkg/cmd/flags/tracee_ebpf_output_test.go [hunk 3]
```diff
@@ -22,22 +22,22 @@ func TestPrepareTraceeEbpfOutput(t *testing.T) {
 			testName:    "invalid output option",
 			outputSlice: []string{"foo"},
 			// it's not the preparer job to validate input. in this case foo is considered an implicit output format.
-			expectedError: errors.New("unrecognized output format: foo. Valid format values: 'table', 'table-verbose', 'json', or 'gotemplate='. Use '--output help' for more info"),
+			expectedError: errors.New("unrecognized output format: foo. Valid format values: 'table', 'table-verbose', 'json', or 'gotemplate='. Use 'tracee man output' for more info"),
```
Comment (josedonizetti) [inline pkg/cmd/flags/tracee_ebpf_output_test.go]:
```suggestion
			expectedError: UnrecognizedOutputFormatError("foo"),
```

File: pkg/cmd/flags/tracee_ebpf_output_test.go [hunk 4]
```diff
@@ -22,22 +22,22 @@ func TestPrepareTraceeEbpfOutput(t *testing.T) {
...
 		},
 		{
 			testName:      "invalid output option",
 			outputSlice:   []string{"option:"},
-			expectedError: errors.New("invalid output option: , use '--output help' for more info"),
+			expectedError: errors.New("invalid output option: , use 'tracee man output' for more info"),
```
Comment (josedonizetti) [inline pkg/cmd/flags/tracee_ebpf_output_test.go]:
```suggestion
			expectedError: InvalidOutputOptionError(""),
```

File: pkg/cmd/flags/tracee_ebpf_output_test.go [hunk 5]
```diff
@@ -22,22 +22,22 @@ func TestPrepareTraceeEbpfOutput(t *testing.T) {
...
 		},
 		{
 			testName:      "invalid output option 2",
 			outputSlice:   []string{"option:foo"},
-			expectedError: errors.New("invalid output option: foo, use '--output help' for more info"),
+			expectedError: errors.New("invalid output option: foo, use 'tracee man output' for more info"),
```
Comment (josedonizetti) [inline pkg/cmd/flags/tracee_ebpf_output_test.go]:
```suggestion
			expectedError: InvalidOutputOptionError("foo"),
```

File: pkg/cmd/flags/tracee_ebpf_output_test.go [hunk 6]
```diff
@@ -22,22 +22,22 @@ func TestPrepareTraceeEbpfOutput(t *testing.T) {
...
 		},
 		{
 			testName:      "empty val",
 			outputSlice:   []string{"out-file"},
-			expectedError: errors.New("unrecognized output format: out-file. Valid format values: 'table', 'table-verbose', 'json', or 'gotemplate='. Use '--output help' for more info"),
+			expectedError: errors.New("unrecognized output format: out-file. Valid format values: 'table', 'table-verbose', 'json', or 'gotemplate='. Use 'tracee man output' for more info"),
```
Comment (josedonizetti) [inline pkg/cmd/flags/tracee_ebpf_output_test.go]:
```suggestion
			expectedError: UnrecognizedOutputFormatError("out-file"),
```

File: pkg/cmd/printer/printer_test.go [hunk 7]
```diff
@@ -24,13 +24,13 @@ func TestTraceeEbpfPrepareOutputPrinterConfig(t *testing.T) {
 			testName:        "invalid format",
 			outputSlice:     []string{"notaformat"},
 			expectedPrinter: config.PrinterConfig{},
-			expectedError:   fmt.Errorf("unrecognized output format: %s. Valid format values: 'table', 'table-verbose', 'json', or 'gotemplate='. Use '--output help' for more info", "notaformat"),
+			expectedError:   fmt.Errorf("unrecognized output format: %s. Valid format values: 'table', 'table-verbose', 'json', or 'gotemplate='. Use 'tracee man output' for more info", "notaformat"),
```
Comment (josedonizetti) [inline pkg/cmd/printer/printer_test.go]:
```suggestion
			expectedError:   flags.UnrecognizedOutputFormatError("notaformat"),
```

File: pkg/cmd/printer/printer_test.go [hunk 8]
```diff
@@ -24,13 +24,13 @@ func TestTraceeEbpfPrepareOutputPrinterConfig(t *testing.T) {
...
 		},
 		{
 			testName:        "invalid format with format prefix",
 			outputSlice:     []string{"format:notaformat2"},
 			expectedPrinter: config.PrinterConfig{},
-			expectedError:   fmt.Errorf("unrecognized output format: %s. Valid format values: 'table', 'table-verbose', 'json', or 'gotemplate='. Use '--output help' for more info", "notaformat2"),
+			expectedError:   fmt.Errorf("unrecognized output format: %s. Valid format values: 'table', 'table-verbose', 'json', or 'gotemplate='. Use 'tracee man output' for more info", "notaformat2"),
```
Comment (josedonizetti) [inline pkg/cmd/printer/printer_test.go]:
```suggestion
			expectedError:   flags.UnrecognizedOutputFormatError("notaformat2"),
```

**Review by josedonizetti — APPROVED** [review]
