### PR TITLE
libbpfgo: Check for ERR_PTR return values

### LINKED ISSUE #691: Tracee panic when cannot allocate memory
Reported by @eidans 

```
michael@MichaelsLenovo:~/workarea/tracee$ sudo ./dist/tracee-ebpf --perf-buffer-size=16384 --security-alerts -t event=execve,security_bprm_check,security_file_open,fork,vfork,clone,sched_process_exit,sec
urity_inode_unlink,ptrace,bpf,process_vm_writev,connect,accept,bind,mem_prot_alert,init_module,finit_module,dup,dup2,dup3,close --output=format:gob | ./dist/tracee-rules --input-tracee=file:stdin --input
-tracee=format:gob
OOOOOOO
Loaded signature(s): [TRC-1 TRC-2 TRC-BYPASS TRC-3 TRC-RUNTIME-CONTAINER-START TRC-RUNTIME-CONTAINER-STOP TRC-4 TRC-5 TRC-6 TRC-7]
libbpf: failed to mmap perf buffer on cpu #7: Cannot allocate memory
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x34 pc=0x642b87]

runtime stack:
runtime.throw(0x7b29b4, 0x2a)
/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 23 [syscall]:
runtime.cgocall(0x631890, 0xc00003a738, 0x0)
/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00003a708 sp=0xc00003a6d0 pc=0x40581b
github.com/aquasecurity/tracee/libbpfgo._Cfunc_perf_buffer__poll(0xfffffffffffffff4, 0xc00000012c, 0x0)
_cgo_gotypes.go:467 +0x48 fp=0xc00003a738 sp=0xc00003a708 pc=0x573388
github.com/aquasecurity/tracee/libbpfgo.(*PerfBuffer).poll.func1(0xc0000b4b70, 0xc000096180)
/root/go/pkg/mod/github.com/aquasecurity/tracee/libbpfgo@v0.0.0-20210318031738-f66f7bedda26/libbpfgo.go:764 +0x65 fp=0xc00003a770 sp=0xc00003a738 pc=0x5783a5
github.com/aquasecurity/tracee/libbpfgo.(*PerfBuffer).poll(0xc0000b4b70, 0x761b40, 0x806d90)
/root/go/pkg/mod/github.com/aquasecurity/tracee/libbpfgo@v0.0.0-20210318031738-f66f7bedda26/libbpfgo.go:764 +0x55 fp=0xc00003a7c8 sp=0xc00003a770 pc=0x576d55
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00003a7d0 sp=0xc00003a7c8 pc=0x46c961
created by github.com/aquasecurity/tracee/libbpfgo.(*PerfBuffer).Start
/root/go/pkg/mod/github.com/aquasecurity/tracee/libbpfgo@v0.0.0-20210318031738-f66f7bedda26/libbpfgo.go:746 +0x3f

 

goroutine 1 [chan receive]:
github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).Run(0xc000128400, 0x0, 0x0)
/home/michael/workarea/tracee/tracee-ebpf/tracee/tracee.go:867 +0x1d0
main.main.func1(0xc000113e80, 0x0, 0x14)
/home/michael/workarea/tracee/tracee-ebpf/main.go:80 +0x685
github.com/urfave/cli/v2.(*App).RunContext(0xc000082a80, 0x843e78, 0xc0000ba010, 0xc000092180, 0x6, 0x6, 0x0, 0x0)
/root/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:311 +0x6fe
github.com/urfave/cli/v2.(*App).Run(...)
/root/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:211
main.main()
/home/michael/workarea/tracee/tracee-ebpf/main.go:144 +0x832

 

goroutine 22 [runnable]:
os/signal.loop()
/usr/local/go/src/os/signal/signal_unix.go:21
created by os/signal.Notify.func1.1
/usr/local/go/src/os/signal/signal.go:151 +0x45
```

Comment from @yanivagman 
```
Cannot allocate memory. The size is in multiples of 4k (page size), so 16k will give 64mb per each cpu
```

### LINKED ISSUE #708: libbpfgo crashes when some of libbpf functions fail
When `libbpf` functions returning pointers fail, they sometimes return a `NULL` and sometimes encode `errno` inside the pointer (by using kernel's `ERR_PTR` mechanism). As such it is not sufficient to just check for NULL as it leads the error to not be detected and causes a subsequent crash.

### PR DESCRIPTION
**Pull request by eyakubovich**
Some libbpf functions fail and return an -errno
encoded inside the pointer. Therefore checking
for NULL is not enough.

Checks the returned pointers for NULL or ERR_PTR
encoding and converts the errno (if available)
to an error message.

Fixes #708 
Fixes #691

### CODE REVIEW

**Comment by yanivagman** [comment]
Thanks @eyakubovich , we also noticed this bug.
Please see #694 which also attempts to fix it.
Your PR seems to handle cases which are not fixed by #694 but I don't see a reason to open a new PR for this.

**Comment by eyakubovich** [comment]
Should've looked at existing PRs before starting.
- This adds the check to more functions that are affected (compared to #694)
- It's best to check for both the NULL and `PTR_ERR` because some functions are not consistent: some code paths return NULL and some use the `ERR_PTR`. I think it's bad form but that's the way it is.

**Comment by yanivagman** [comment]
@simar7

File: libbpfgo/libbpfgo.go [hunk 1]
```diff
@@ -260,14 +278,25 @@ func bumpMemlockRlimit() error {
 	return nil
 }
 
+func errnoError(ptr unsafe.Pointer, errFmt string, args... interface{}) error {
+	negErrno := C.PTR_ERR(ptr)
+	errno := syscall.Errno(-int64(negErrno))
+	if errno == 0 {
+		return fmt.Errorf(errFmt, args...)
+	} else {
```
Comment (simar7) [inline libbpfgo/libbpfgo.go:286]: nit: you can drop this else as there's already a `return` in the if.

File: libbpfgo/libbpfgo.go [hunk 2]
```diff
@@ -260,14 +278,25 @@ func bumpMemlockRlimit() error {
...
 func NewModuleFromFile(bpfObjFile string) (*Module, error) {
 	C.set_print_fn()
 	bumpMemlockRlimit()
 	cs := C.CString(bpfObjFile)
 	obj := C.bpf_object__open(cs)
 	C.free(unsafe.Pointer(cs))
-	if obj == nil {
-		return nil, fmt.Errorf("failed to open BPF object %s", bpfObjFile)
+	if C.IS_ERR_OR_NULL(unsafe.Pointer(obj)) {
+		return nil, errnoError(unsafe.Pointer(obj), "failed to open BPF object %s", bpfObjFile)
```
Comment (simar7) [inline libbpfgo/libbpfgo.go:299]: Maybe this is a good time to add a unit test for this function in order to avoid such scenarios in the future.

Comment (simar7) [reply libbpfgo/libbpfgo.go:299]: ditto elsewhere where the check is done

Comment (eyakubovich) [reply libbpfgo/libbpfgo.go:299]: I think it would be beneficial to use a unit testing framework (builtin or `check`) instead of standalone selftests.
Should that be a separate issue/PR though?

Comment (simar7) [reply libbpfgo/libbpfgo.go:299]: A simple unit test would suffice IMO. I usually like to write the test for the change of code along with it.

Comment (eyakubovich) [reply libbpfgo/libbpfgo.go:299]: I agree, I'm saying that libbpfgo as a whole is missing unit tests. It would be beneficial for write the tests that cover the whole lib.

But I'll kick things off by adding at least a test for a one or two of these functions.

Comment (eyakubovich) [reply libbpfgo/libbpfgo.go]: I added the tests but nothing is running them yet. I used `//go:generate` instead of a `Makefile` (can change it) so the CI would need to run `go generate` prior to running `go test`. PTAL and let me know how to best invoke them in CI.

The tests also require 5.8+ kernel because of `AttachLSM` although I can put it behind a flag or something.

Comment (eyakubovich) [reply libbpfgo/libbpfgo.go]: /cc @simar7

Comment (simar7) [reply libbpfgo/libbpfgo.go]: Thanks I will take a look at it shortly and get back to you.

Comment (simar7) [reply libbpfgo/libbpfgo.go]: > I added the tests but nothing is running them yet. I used `//go:generate` instead of a `Makefile` (can change it) so the CI would need to run `go generate` prior to running `go test`. PTAL and let me know how to best invoke them in CI.
> 
> The tests also require 5.8+ kernel because of `AttachLSM` although I can put it behind a flag or something.

Thanks this looks wonderful @eyakubovich! Looks like it just needs to be told where to find the right headers:

```
vagrant@ubuntu-groovy:/usr/vagrant/repos/tracee/libbpfgo$ go generate
test/test.bpf.c:3:10: fatal error: 'bpf/bpf_helpers.h' file not found
#include <bpf/bpf_helpers.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
libbpfgo_test.go:2: running "clang": exit status 1
```

As you mentioned it would be better to add them to run via the Makefile as some of the pre-requisite headers will be set in it. We currently do this for running perfbuffer and ringbuffer tests and you can find an example here: https://github.com/aquasecurity/tracee/blob/77cf435059442695b6b604630406ddc8614820e8/libbpfgo/selftest/perfbuffers/Makefile#L4-L7

Comment (eyakubovich) [reply libbpfgo/libbpfgo.go]: @simar7 PTAL. The tests fail on CI (as expected, kernel version) so I didn't add them to the GH actions. Can you check if they run for you? I'm a bit surprised that `#include <bpf/bpf_helpers.h>` failed -- if libbpf is installed, it should be in `/usr/include` and should work. If it's installed elsewhere, I guess the user will need to specify.

Comment (simar7) [reply libbpfgo/libbpfgo.go]: Once we sort the running of the tests locally, we are good to merge this in. Appreciate your patience.

**Comment by yanivagman** [comment]
@simar7 any reason why not to merge this PR now?
This is an important bug fix, and we can take care of any other required test additions after we merge this

**Comment by simar7** [comment]
> @simar7 any reason why not to merge this PR now?
> This is an important bug fix, and we can take care of any other required test additions after we merge this

I'm still unable to run the added tests. Merging an important bug fix without adding a test that exercises it seems like an omission to me. If you think that's fine, we can merge it.

**Review by simar7 — APPROVED** [review]
