### PR TITLE
fix multiple symbols prints bug

### LINKED ISSUE #2993: print_mem_dump error on multiple symbols
## Description

When tracee-ebpf is run like so:
`sudo dist/tracee-ebpf -f e=print_mem_dump -f print_mem_dump.args.symbol_name=execve,kill`
to print the memory of execve and kill symbols the following error is displayed:
```
TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
{"level":"error","ts":1681140625.945699,"msg":"Error processing event","event":"print_mem_dump","error":"ebpf.(*Tracee).processTriggeredEvent: failed to apply invoke context on print_mem_dump event: no event context with id 1"}
{"level":"error","ts":1681140625.9457588,"msg":"Tracee encountered an error","error":"ebpf.(*Tracee).processTriggeredEvent: failed to apply invoke context on print_mem_dump event: no event context with id 1"}
02:00:00:000000  0                       0       0       0                print_mem_dump            bytes: [15 31 68 0 0 85 72 137 229 65 84 83 72 139 95 96 76 139 103 104 72 139 127 112 232 163 173 0 0 73 137 217 76 137 225 69 49 192 106 0 72 137 198 49 210 191 156 255 255 255 232 137 251 255 255 72 141 101 240 91 72 152 65 92 93 195 204 204 204 204 102 46 15 31 132 0 0 0 0 0 15 31 68 0 0 85 72 137 229 65 84 83 72 139 95 96 76 139 103 104 72 139 127 112 232 83 173 0 0 73 137 217 76 137 225 186 1 0 0 0 106 0 72 137 198 65 184], address: 0xffffffff8e18cc40, length: 127, caller_context_id: 1, arch: x86_64, symbol_name: __x64_sys_execve, symbol_owner: system

```

## Output of `tracee -v`:

```
Tracee version "v0.13.1-10-g90f56d07"
```

## Output of `uname -a`:

```
Linux ubuntu 5.15.0-50-generic #56~20.04.1-Ubuntu SMP Tue Sep 27 15:51:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

## Additional details 

It seems that this if statement should be true:
https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/events_processor.go#L369

But it isn't...

### PR DESCRIPTION
**Pull request by AsafEitani**
### 1. Explain what the PR does

Fix a bug related to the context saved on the `print_mem_dump` event.

fix #2993 
### 2. Explain how to test it

run `dist/tracee-ebpf -f e=print_mem_dump -f print_mem_dump.args.symbol_name=execve,kill` and see if there are errors

### CODE REVIEW

File: pkg/ebpf/tracee.go [hunk 1]
```diff
@@ -1695,7 +1693,9 @@ func (t *Tracee) triggerMemDump(event trace.Event) error {
 				if err != nil {
 					return errfmt.WrapError(err)
 				}
-				_ = t.triggerMemDumpCall(address, length, uint64(eventHandle))
+				eventHandle := t.triggerContexts.Store(event)
+				fmt.Printf("AAAAAAAAAAAAAAAAAAAAAA%d\n", eventHandle)
```
Comment (NDStrahilevitz) [inline pkg/ebpf/tracee.go:1697]: leftover

**Review by NDStrahilevitz — APPROVED** [review]
LGTM, please fix the leftover and we can merge

**Comment by rafaeldtinoco** [comment]
Don't forget the line breaks in git log messages, please.
