### PR TITLE
fix(events): fix `process_execute_failed` missing symbol for new kernels

### LINKED ISSUE #3356: Missing symbols on newer kernels (> ~6.3)
## Description

I noticed that my 6.3.6 machine is missing the following symbols:
* `exec_binprm` - part of the `process_execute_failed` event
* `layout_and_allocate` - part of the `module_load` event

## Output of `tracee version`:

```
v0.16.1
```

## Output of `uname -a`:

```
Linux Alon-Zivony 6.3.6-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Mon Jun 12 11:59:43 IDT 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### LINKED ISSUE #3727: Tracee has too many errors when running in v6.5 with a real world cmdline/policy
## Description

From https://github.com/aquasecurity/tracee/issues/3357#issuecomment-1838621610

```
$ sudo ./dist/tracee --no-containers -p ~/work/cli/test/ -o option:exec-env -o option:e
xec-hash -o option:parse-arguments -o option:sort-events -o none
{"level":"warn","ts":1701694975.813535,"msg":"libbpf: prog 'trace_ret_layout_and_allocate': failed to create kretprobe 'layout_and_allocate+0x0' perf event: No such file or directory"}
{"level":"error","ts":1701694975.8135998,"msg":"Event canceled because of missing probe dependency","missing probe":102,"event":"hidden_kernel_module_seeker"}
{"level":"warn","ts":1701694975.9879267,"msg":"libbpf: prog 'trace_ret_exec_binprm': failed to create kretprobe 'exec_binprm+0x0' perf event: No such file or directory"}
{"level":"error","ts":1701694975.9879916,"msg":"Event canceled because of missing probe dependency","missing probe":96,"event":"process_execute_failed"}
{"level":"warn","ts":1701694976.1228976,"msg":"libbpf: prog 'trace_load_elf_phdrs': failed to create kprobe 'load_elf_phdrs+0x0' perf event: Cannot assign requested address"}
{"level":"warn","ts":1701694976.2762296,"msg":"libbpf: prog 'trace_exec_binprm': failed to create kprobe 'exec_binprm+0x0' perf event: No such file or directory"}
{"level":"error","ts":1701694976.27629,"msg":"Event canceled because of missing probe dependency","missing probe":95,"event":"process_execute_failed"}
{"level":"warn","ts":1701694979.5936491,"msg":"Memory dump","error":"ebpf.(*Tracee).triggerMemDump: policy 0: no address or symbols were provided to print_mem_dump event. please provide it via -e print_mem_dump.args.address=<hex address>, -e print_mem_dump.args.symbol_name=<owner>:<symbol> or -e print_mem_dump.args.symbol_name=<symbol> if specifying a system owned symbol"}
{"level":"warn","ts":1701694979.5936863,"msg":"Memory dump","error":"ebpf.(*Tracee).triggerMemDump: policy 1: invalid symbols provided to print_mem_dump event: {system_,sys_,__x64_sys_,__arm64_sys_}compat_filldir64"}
{"level":"warn","ts":1701694979.5936952,"msg":"Memory dump","error":"ebpf.(*Tracee).triggerMemDump: policy 1: invalid symbols provided to print_mem_dump event: {system_,sys_,__x64_sys_,__arm64_sys_} "}
{"level":"warn","ts":1701694979.5937037,"msg":"Memory dump","error":"ebpf.(*Tracee).triggerMemDump: policy 2: no address or symbols were provided to print_mem_dump event. please provide it via -e print_mem_dump.args.address=<hex address>, -e print_mem_dump.args.symbol_name=<owner>:<symbol> or -e print_mem_dump.args.symbol_name=<symbol> if specifying a system owned symbol"}
{"level":"warn","ts":1701694979.5937123,"msg":"Memory dump","error":"ebpf.(*Tracee).triggerMemDump: policy 3: no address or symbols were provided to print_mem_dump event. please provide it via -e print_mem_dump.args.address=<hex address>, -e print_mem_dump.args.symbol_name=<owner>:<symbol> or -e print_mem_dump.args.symbol_name=<symbol> if specifying a system owned symbol"}
```

In here we are seeing multiple issues when running Tracee in a v6.5 kernel:

1. symbols from the "hidden kernel module" logic that are required and don't exit https://github.com/aquasecurity/tracee/issues/3356
2. cancelled event "error" (should it be an error ?)
3. process_execute fails due to the lack of "exec_binprm" hook. https://github.com/aquasecurity/tracee/issues/3356
4. load_elf_phdrs fails due to the lack of missing hook. https://github.com/aquasecurity/tracee/issues/3653
5. bad symbols being used/given to print_mem_dump

### LINKED ISSUE #4008: User-mode events cannot be used as dependencies
## Description

User mode event currently are only created if they should be emitted.
However, if an event use them as a dependency, it means it won't be created at all.

## Output of `tracee version`:

```
(paste your output here)
```

## Output of `uname -a`:

```
(paste your output here)
```

### PR DESCRIPTION
**Pull request by AlonZivony**
### 1. Explain what the PR does

Fix the `process_execute_failed` event missing probe error for kernel 5.8 forward.
This is a quick fix, as it uses a global value to determine which probes to use.
In the future, it should be determined using the fallback mechanism - #3965.
This is the fast fix for the previous PR #3881.

Fix #3356
Also fix #3727 as this is the last step for it to be fixed.
On the way fix #4008

### CODE REVIEW

**Comment by geyslan** [comment]
Going over this today. 👍🏼

File: pkg/ebpf/tracee.go [hunk 1]
```diff
@@ -1492,35 +1492,39 @@ func (t *Tracee) invokeInitEvents(out chan *trace.Event) {
 		event.MatchedPolicies = pols.MatchedNames(matchedPolicies)
 	}
 
+	policiesMatch := func(state events.EventState) uint64 {
+		return state.Emit | state.Submit
+	}
```
Comment (geyslan) [inline pkg/ebpf/tracee.go:1515]: @AlonZivony, did we have an open issue for this?

File: pkg/ebpf/probes/probe_group.go [hunk 2]
```diff
@@ -229,6 +230,8 @@ func NewDefaultProbeGroup(module *bpf.Module, netEnabled bool, kSyms *helpers.Ke
 		SignalSchedProcessFork:     NewTraceProbe(RawTracepoint, "sched:sched_process_fork", "sched_process_fork_signal"),
 		SignalSchedProcessExec:     NewTraceProbe(RawTracepoint, "sched:sched_process_exec", "sched_process_exec_signal"),
 		SignalSchedProcessExit:     NewTraceProbe(RawTracepoint, "sched:sched_process_exit", "sched_process_exit_signal"),
+		ExecuteFinisehd:            NewTraceProbe(Tracepoint, "syscalls:sys_exit_execve", "execute_finished"),
+		ExecuteAtFinisehd:          NewTraceProbe(Tracepoint, "syscalls:sys_exit_execveat", "execute_finished"),
```
Comment (geyslan) [inline pkg/ebpf/probes/probe_group.go:234]:
```suggestion
		ExecuteAtFinished:          NewTraceProbe(Tracepoint, "syscalls:sys_exit_execveat", "execute_finished"),
```

File: pkg/ebpf/probes/probes.go [hunk 3]
```diff
@@ -138,4 +139,6 @@ const (
 	SignalSchedProcessFork
 	SignalSchedProcessExec
 	SignalSchedProcessExit
+	ExecuteFinisehd
+	ExecuteAtFinisehd
```
Comment (geyslan) [inline pkg/ebpf/probes/probes.go:143]: ditto and for all occurrences below...

```suggestion
	ExecuteFinished
	ExecuteAtFinished
```

File: tests/e2e-inst-test.sh [hunk 4]
```diff
@@ -129,7 +129,7 @@ for TEST in $TESTS; do
         --output option:parse-arguments \
         --log file:$SCRIPT_TMP_DIR/tracee-log-$$ \
         --signatures-dir "$SIG_DIR" \
-        --scope comm=echo,mv,ls,tracee,proctreetester,ping,ds_writer,fsnotify_tester \
+        --scope comm=echo,mv,ls,tracee,proctreetester,ping,ds_writer,fsnotify_tester,process_execute,tracee-ebpf \
```
Comment (geyslan) [inline tests/e2e-inst-test.sh:132]: Unrelated to this PR, but I think that in other PR we should make the scope option trim the specified values to the 16 char limit, so passing an expected value like "process_execute_failed" would work since the trim will avoid the NUL overwrite.

**Review by geyslan — APPROVED** [review]
LGTM

**Comment by AlonZivony** [comment]
@geyslan if you can make sure this PR is getting into the 0.21 version it would be great.

**Comment by geyslan** [comment]
> @geyslan if you can make sure this PR is getting into the 0.21 version it would be great.

This one went unnoticed, sorry. We filter by kind/bug label to check if a PR needs to enter before the RC. Probably some issue or this PR did not have the label and this one was left out. But let's fix it.

**Comment by geyslan** [comment]
E2E 1483 green.

**Comment by geyslan** [comment]
Backport: https://github.com/aquasecurity/tracee/pull/4011
