### PR TITLE
fix: remove unneeded SYSLOG capability from base capabilities

### LINKED ISSUE #3079: remove unneeded base capability SYSLOG
Currently `hooked_syscalls`,`hooked_seq_ops`,`hooked_proc_fops` and `print_mem_dump` are setting the base capability as SYSLOG, although it's only required when updating or reading the kallsyms file.

We want to change that so the capabilities are used only when the kallsyms file is needed.

### PR DESCRIPTION
**Pull request by yanivagman**
### 1. Explain what the PR does

Remove SYSLOG from base capabilities of hooked_syscall, hooked_seq_ops, hooked_proc_fops, and print_mem_dump events. Add proper capability elevation when kallsyms access is actually needed.

Fixes #3079

### CODE REVIEW

File: pkg/ebpf/tracee.go [hunk 1]
```diff
@@ -1903,11 +1910,15 @@ func (t *Tracee) triggerMemDump(event trace.Event) []error {
...
-						symbol, errSyscall = t.getKernelSymbols().GetSymbolByOwnerAndName(owner, prefix+name)
-						if errSyscall == nil {
-							err = nil
+						err = capabilities.GetInstance().Specific(
+							func() error {
+								var capErr error
+								symbol, capErr = t.getKernelSymbols().GetSymbolByOwnerAndName(owner, prefix+name)
+								return capErr
+							},
+							cap.SYSLOG) // Required to read /proc/kallsyms
```
Comment (josedonizetti) [inline pkg/ebpf/tracee.go]: does it make sense to raise/lower capabilities per prefix, since we have only 3 prefixes, wouldn't it be better do the for inside the Specific, and don't change caps several times?

File: pkg/events/derive/hooked_syscall.go [hunk 2]
```diff
@@ -53,7 +55,14 @@ func deriveDetectHookedSyscallArgs(kernelSymbols *environment.KernelSymbolTable)
...
 
-		hookedFuncSymbols, err := kernelSymbols.GetSymbolByAddr(address)
+		var hookedFuncSymbols []*environment.KernelSymbol
+		err = capabilities.GetInstance().Specific(
+			func() error {
+				var capErr error
+				hookedFuncSymbols, capErr = kernelSymbols.GetSymbolByAddr(address)
+				return capErr
+			},
+			cap.SYSLOG) // Required to read /proc/kallsyms
```
Comment (josedonizetti) [inline pkg/events/derive/hooked_syscall.go:66]: as we don't return the error back, only a fixed value, and error as nil, perhaps we should log.Error if error is differen than nil?

File: pkg/ebpf/tracee.go (hunk 1 above)
Comment (yanivagman) [reply pkg/ebpf/tracee.go]: You are absolutely right with that point!

File: pkg/events/derive/hooked_syscall.go (hunk 2 above)
Comment (yanivagman) [reply pkg/events/derive/hooked_syscall.go:66]: What do you mean we don't return the error back? isn't capErr what we get in err back?

Comment (josedonizetti) [reply pkg/events/derive/hooked_syscall.go:66]:
```
var hookedFuncSymbols []*environment.KernelSymbol
err = capabilities.GetInstance().Specific(
	func() error {
		var capErr error
		hookedFuncSymbols, capErr = kernelSymbols.GetSymbolByAddr(address)
		return capErr
	},
	cap.SYSLOG) // Required to read /proc/kallsyms

// if err is different than nil, we return [][]{...}, **nil**
// so we don't know whatever was inside the error itself, 
// perhaps logging it here, so we know such a func is returning an error? 
if err != nil {
    return [][]interface{}{{syscallName, hexAddress, "", ""}}, nil
}
```

Comment (yanivagman) [reply pkg/events/derive/hooked_syscall.go:66]: Ok, now I see what you mean. This part of the code wasn't change in this PR and we didn't return the error from GetSymbolByAddr before as well. Anyway, this is a good point. I'll add this
