### PR TITLE
tracee-ebpf: fix container removal in cgroup v1

### LINKED ISSUE #1534: Missing container ids
Container removal didn't take into account cgroup hierarchy id, unlike cgroupMkdir (container creation).
Under cgroup v1 environments, this might cause running containers to be removed before they are actually removed. In case another container has the same cgroup id, but in another cgroup hierarchy, the removal of such a container will also remove the first one.

### PR DESCRIPTION
**Pull request by yanivagman**
Container removal didn't take into account cgroup hierarchy id, unlike
cgroupMkdir (container creation).
Under cgroup v1 environments, this might cause running containers to be
removed before they are actually removed. In case another container has
the same cgroup id, but in another cgroup hierarchy, the removal of such
a container will also remove the first one.

Fix this by updating the container maps for only one cgroup hierarchy (cpuset).

Close #1534

### CODE REVIEW

File: pkg/containers/containers.go [hunk 1]
```diff
@@ -41,25 +41,31 @@ type CgroupInfo struct {
...
 // InitContainers initializes a Containers object and returns a pointer to it.
 // User should further call "Populate" and iterate with Containers data.
-func InitContainers() *Containers {
+func InitContainers() (*Containers, error) {
 	cgroupV1 := false
 	if _, err := os.Stat("/sys/fs/cgroup/cgroup.controllers"); os.IsNotExist(err) {
 		cgroupV1 = true
-		initCgroupV1()
+		if err := initCgroupV1(); err != nil {
+			return nil, nil
```
Comment (grantseltzer) [inline pkg/containers/containers.go:49]: Shouldn't this return an error? If not perhaps a debug statement?

File: pkg/containers/containers.go [hunk 2]
```diff
@@ -71,14 +77,11 @@ func (c *Containers) Populate() error {
...
-func initCgroupV1() {
-	// Set hierarchy ID to 1 as a fallback in case of an error
-	cgroupV1HierarchyID = 1
-
+func initCgroupV1() error {
 	cgroupsFile := "/proc/cgroups"
 	file, err := os.Open(cgroupsFile)
 	if err != nil {
-		return
+		return err
```
Comment (grantseltzer) [inline pkg/containers/containers.go:84]:
```suggestion
		return fmt.Errorf("could not open cgroups file %s: %w", cgroupsFile, err)
```

File: pkg/containers/containers.go [hunk 3]
```diff
@@ -90,10 +93,13 @@ func initCgroupV1() {
 		}
 		intID, err := strconv.Atoi(sline[1])
 		if err != nil || intID < 0 {
-			return
+			return fmt.Errorf("error parsing /proc/cgroups")
```
Comment (grantseltzer) [inline pkg/containers/containers.go:96]:
```suggestion
			return fmt.Errorf("error parsing /proc/cgroups: %w", err)
```

File: pkg/ebpf/events_processor.go [hunk 4]
```diff
@@ -328,7 +327,11 @@ func (t *Tracee) processEvent(event *trace.Event) error {
 		if err != nil {
 			return fmt.Errorf("error parsing cgroup_rmdir args: %v", err)
 		}
-		t.containers.CgroupRemove(cgroupId)
+		hId, err := getEventArgUint32Val(event, "hierarchy_id")
+		if err != nil {
+			return fmt.Errorf("error parsing cgroup_mkdir args: %v", err)
```
Comment (grantseltzer) [inline pkg/ebpf/events_processor.go:332]:
```suggestion
			return fmt.Errorf("error parsing cgroup_mkdir args: %w", err)
```

File: pkg/ebpf/tracee.go [hunk 5]
```diff
@@ -260,7 +260,10 @@ func New(cfg Config) (*Tracee, error) {
 		}
 	}
 
-	c := containers.InitContainers()
+	c, err := containers.InitContainers()
+	if err != nil {
+		return nil, fmt.Errorf("error initializing containers: %v", err)
```
Comment (grantseltzer) [inline pkg/ebpf/tracee.go:265]:
```suggestion
		return nil, fmt.Errorf("error initializing containers: %w", err)
```

**Review by grantseltzer — COMMENTED** [review]
Since I can't reproduce this (Yaniv and I spoke offline about how it can be produced in a specific sandbox), can someone who can confirm this fixes the issue approve this? I just had a couple comments about errors.

File: pkg/containers/containers.go (hunk 1 above)
Comment (yanivagman) [reply pkg/containers/containers.go:49]: Yes, you are right. Good catch

**Comment by OriGlassman** [comment]
> Since I can't reproduce this (Yaniv and I spoke offline about how it can be produced in a specific sandbox), can someone who can confirm this fixes the issue approve this? I just had a couple comments about errors.

Based on an environment that this bug was detected on, it no longer occurs and indeed seems to address the issue.

**Comment by rafaeldtinoco** [comment]
Reviewing this now...

**Review by rafaeldtinoco — APPROVED** [review]
That is a nice catch! This way, if another cgroup controller directory is being removed we don't remove the container until the cpuset controller directory is removed (and then we still wait sometime on the deletion logic we already had).
