### PR TITLE
fix(printer): flush JSON output immediately to stdout/stderr

### LINKED ISSUE #5162: Events not printed immediately when using json output
## Description

When using JSON output (`-o json`), events don't get printed immediately when they are created.

To reproduce, run using the `init_namespaces` event which should only output 1 event, and see how it doesn't get printed until tracee is stopped:

`sudo dist/tracee -e init_namespaces -o json`

## Output of `tracee version`:

```
Tracee version: main-e232fca4a
```

## Output of `uname -a`:

```
Linux ********** 6.6.36.6-microsoft-standard-WSL2 #4 SMP PREEMPT_DYNAMIC Mon Feb 10 18:30:07 IST 2025 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by yanivagman**
Events were not printed immediately when using -o json due to buffering. Added intelligent flush strategy that detects stdout/stderr and flushes immediately for interactive output while maintaining buffered writes for file output to preserve performance.

Fixes #5162

### CODE REVIEW

File: pkg/cmd/printer/printer.go [hunk 1]
```diff
@@ -441,14 +441,24 @@ func (p templateEventPrinter) Close() {
...
 // Init initializes the jsonEventPrinter with a buffered writer.
 func (p *jsonEventPrinter) Init() error {
+	// Detect if output is stdout/stderr for immediate flushing (interactive use)
+	// vs file output where we want buffering for performance
+	if f, ok := p.out.(*os.File); ok {
+		p.isStdoutOrStderr = f == os.Stdout || f == os.Stderr
+	} else {
+		// Default to non-interactive (buffered) for unknown writers
+		p.isStdoutOrStderr = false
+	}
```
Comment (josedonizetti) [inline pkg/cmd/printer/printer.go]: no need for else, it will be false by default

**Comment by oshaked1** [comment]
Looks like the previous flush logic of once a second should be good enough, but for some reason it wasn't working (in the example I gave in the issue the event was not printed at all until tracee was stopped, even waiting much longer than a second).

**Comment by yanivagman** [comment]
> Looks like the previous flush logic of once a second should be good enough, but for some reason it wasn't working (in the example I gave in the issue the event was not printed at all until tracee was stopped, even waiting much longer than a second).

The thing is that in your case, there is only one event, thus the json Print method will only be called once, and will never reach the 1 sec logic again

**Comment by oshaked1** [comment]
> > Looks like the previous flush logic of once a second should be good enough, but for some reason it wasn't working (in the example I gave in the issue the event was not printed at all until tracee was stopped, even waiting much longer than a second).
> 
> The thing is that in your case, there is only one event, thus the json Print method will only be called once, and will never reach the 1 sec logic again

Isn't this a problem for other output methods/destinations as well? Say we have a policy with a few signatures, a signature event will only be emitted once another signature is triggered.

**Comment by yanivagman** [comment]
> > > Looks like the previous flush logic of once a second should be good enough, but for some reason it wasn't working (in the example I gave in the issue the event was not printed at all until tracee was stopped, even waiting much longer than a second).
> > 
> > 
> > The thing is that in your case, there is only one event, thus the json Print method will only be called once, and will never reach the 1 sec logic again
> 
> Isn't this a problem for other output methods/destinations as well? Say we have a policy with a few signatures, a signature event will only be emitted once another signature is triggered.

The buffering only exists when writing json to a file.
For table output we don't use buffer since we assume an interactive user.
For grpc there is no buffering as well.

**Comment by geyslan** [comment]
I've implemented a fix for the old v0.22.4 internally. Please check the invoke init events function in the private release-v0.22.4 branch.
