### PR TITLE
fix: consistent time conversion for process hash calculation

### LINKED ISSUE #4868: Inconsistent time conversion for process hash calculation between procfs and kernel signals
## Description

While testing and using proctree, I observed that the process hashes obtained from procfs and those from kernel signals differ for the same process.

This happens in two main scenarios:

* When proctree is initially populated from procfs (I'm running Tracee with `--proctree source=both`), and a signal for a new process (`sched_process_exec` or `sched_process_fork`) arrives, the `FeedFromFork` and `FeedFromExec` handlers read the `parent_start_time` and calculate the parent hash.
* When `ProcFSLoop` runs at runtime, it fails to recognize that some processes already exist in the tree because the hash calculated from `procfs` differs from the one calculated from the signal.

From my debugging, I identified two causes:

In the `procfs` functions (`getProcessByPID`, `dealWithProc`, `dealWithThread`), the start time isn't converted to epoch time before hashing. Currently, it uses `startTimeNs := traceetime.ClockTicksToNsSinceBootTime(statStartTime)` ([link](https://github.com/aquasecurity/tracee/blob/33b1b84af93b4d68edf82f31ba2cd3b99cf404e0/pkg/proctree/proctree_procfs.go#L111)), but I believe it should be `startTimeNs := traceetime.BootToEpochNS(traceetime.ClockTicksToNsSinceBootTime(statStartTime))` to match the behavior used during signal handling.

When converting `start_time` from boot to nanoseconds, the result from `procfs` ends in multiple zeros (e.g., `1524976120000000`), while the kernel signal provides a more precise value (e.g., `1524976129897580`) for the same process.

If Tracee consistently uses boot time (not epoch time) to calculate hashes, this issue would be avoided. The hash function already rounds the `start_time` (arg2) to the nearest `10^7`, so using boot time directly ensures consistency. The problem arises when we convert to epoch time: the rounding leads to mismatched hashes, for example:

Signal: `1524976129897580 + 1754327201505193969 = 1755852177635091549 → rounded → 1755852177630000000`
Procfs: `1524976120000000 + 1754327201505193969 = 1755852177625193969 → rounded → 1755852177620000000`

This rounding difference causes the hash mismatch.

## Output of `tracee version`:

main-31145606f

## Output of `uname -a`:

Linux hutesh-tracee-1.c.security-tools-cluster.internal 6.11.0-1017-gcp #17~24.04.1-Ubuntu SMP Thu Jun 26 00:43:22 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by yanivagman**
### 1. Explain what the PR does

Fix inconsistent time conversion between procfs and kernel signals that caused proctree hash mismatches for the same process.

- Convert boot time to epoch time before hash calculation in procfs functions
- Ensure hash consistency between procfs (dealWithProc/dealWithThread) and kernel signal processing (FeedFromFork/FeedFromExec)
- Add comprehensive test that reproduces the bug and verifies the fix

Fixes #4868

### CODE REVIEW

File: pkg/proctree/proctree_procfs.go [hunk 1]
```diff
@@ -158,8 +158,9 @@ func dealWithProc(pt *ProcessTree, givenPid int32) error {
```
Comment (josedonizetti) [inline pkg/proctree/proctree_procfs.go:160]: should `getProcessByPID` also use epochTimeNs? https://github.com/aquasecurity/tracee/blob/38833cc906466d311365afcdb02ec03cc4962549/pkg/proctree/proctree_procfs.go#L110-L112

File: pkg/proctree/proctree_procfs.go [hunk 2]
```diff
@@ -158,8 +158,9 @@ func dealWithProc(pt *ProcessTree, givenPid int32) error {
 
 	// thread start time (monotonic boot)
 	startTimeNs := traceetime.ClockTicksToNsSinceBootTime(start)
-	// process hash
-	hash := utils.HashTaskID(uint32(pid), startTimeNs)
+	// process hash (using epoch time for consistency with kernel signals)
+	epochTimeNs := traceetime.BootToEpochNS(startTimeNs)
+	hash := utils.HashTaskID(uint32(pid), epochTimeNs)
```
Comment (josedonizetti) [inline pkg/proctree/proctree_procfs.go:165]: extract a func?

File: pkg/proctree/proctree_procfs.go (hunk 1 above)
Comment (yanivagman) [reply pkg/proctree/proctree_procfs.go:160]: I think you are absolutely right about that!

File: pkg/proctree/proctree_procfs.go (hunk 2 above)
Comment (yanivagman) [reply pkg/proctree/proctree_procfs.go:165]: startTimeNs is used below so calculating it in a func will require doing it twice.
And I don't think it is worth creating a func for the two next lines

File: pkg/proctree/proctree_test.go [hunk 3]
```diff
@@ -58,3 +60,52 @@ func TestProcessTreeConcurrency(t *testing.T) {
...
+
+	// Simulate realistic scenario from the bug report
+	// System has been running for some time, so boot time != epoch time
+	bootTimeOffssetNs := uint64(1754327201505193969)              // Boot time offset from bug report
+	processStartBootNs := uint64(1524976129897580)                // Process start time since boot (from signal)
+	processStartEpochNs := bootTimeOffssetNs + processStartBootNs // Total epoch time
+
+	// OLD approach (what procfs was doing WRONG)
+	// It was using boot time directly for hash calculation
+	oldProcfsHash := utils.HashTaskID(pid, processStartBootNs)
```
Comment (LucaRocco) [inline pkg/proctree/proctree_test.go]: For clarity, `processStartBootNs` should be `processStartBootNsFromProcfs` (1524976120000000) instead of `processStartBootNsFromSignal`. Practically, this doesn’t change much because HashTaskID already applies rounding, but since we have the variable, I’d prefer to use it.

File: pkg/proctree/proctree_test.go [hunk 4]
```diff
@@ -58,3 +60,52 @@ func TestProcessTreeConcurrency(t *testing.T) {
...
+
+	// NEW approach (what procfs does now CORRECTLY)
+	// Convert boot time to epoch time before hash calculation
+	newProcfsHash := utils.HashTaskID(pid, processStartEpochNs)
```
Comment (LucaRocco) [inline pkg/proctree/proctree_test.go]: Here the number should be `(1754327201505193969 + 1524976120000000) = 1755852177625193969`, so `processStartEpochNsFromProcfs` should be used. This is because you need to use the `start_time` coming from the procfs which, as explained [here](https://github.com/aquasecurity/tracee/issues/4868) and in the previous comment it is converted to nanoseconds

File: pkg/proctree/proctree_test.go [hunk 5]
```diff
@@ -58,3 +60,52 @@ func TestProcessTreeConcurrency(t *testing.T) {
...
+func TestHashCalculationConsistency(t *testing.T) {
+	t.Parallel()
+
+	// Test data representing the same process
+	pid := uint32(12345)
+
+	// Simulate realistic scenario from the bug report
+	// System has been running for some time, so boot time != epoch time
+	bootTimeOffssetNs := uint64(1754327201505193969)              // Boot time offset from bug report
+	processStartBootNs := uint64(1524976129897580)                // Process start time since boot (from signal)
```
Comment (LucaRocco) [inline pkg/proctree/proctree_test.go]: I would change it to `processStartBootNsFromSignal := uint64(1524976129897580)` and add a new variable `processStartBootNsFromProcfs := uint64(1524976120000000)`

File: pkg/proctree/proctree_test.go [hunk 6]
```diff
@@ -58,3 +60,52 @@ func TestProcessTreeConcurrency(t *testing.T) {
...
+	processStartEpochNs := bootTimeOffssetNs + processStartBootNs // Total epoch time
```
Comment (LucaRocco) [inline pkg/proctree/proctree_test.go]: I would change it to `processStartEpochNsFromSignal := bootTimeOffsetNs + processStartBootNsFromSignal` and add a new variable `processStartEpochNsFromProcfs := bootTimeOffsetNs + processStartBootNsFromProcfs`

File: pkg/proctree/proctree_test.go [hunk 7]
```diff
@@ -58,3 +60,52 @@ func TestProcessTreeConcurrency(t *testing.T) {
...
+	// It was using boot time directly for hash calculation
+	oldProcfsHash := utils.HashTaskID(pid, processStartBootNs)
+
+	// NEW approach (what procfs does now CORRECTLY)
+	// Convert boot time to epoch time before hash calculation
+	newProcfsHash := utils.HashTaskID(pid, processStartEpochNs)
+
+	// Kernel signal approach (what kernel signals always did CORRECTLY)
+	// Kernel signals provide epoch time directly
+	kernelSignalHash := utils.HashTaskID(pid, processStartEpochNs)
```
Comment (LucaRocco) [inline pkg/proctree/proctree_test.go]: Here the variable `processStartEpochNsFromSignal` should be used

File: pkg/proctree/proctree_test.go [hunk 8]
```diff
@@ -58,3 +60,52 @@ func TestProcessTreeConcurrency(t *testing.T) {
...
+
+	// Verify that the new procfs approach matches kernel signals (THE FIX)
+	if newProcfsHash != kernelSignalHash {
```
Comment (LucaRocco) [inline pkg/proctree/proctree_test.go:93]: By applying the previous comments this check makes sense. Currently `newProcfsHash` and `kernelSignalHash` are calculated with the same exact number (`processStartEpochNs`) so the check will be always false.

File: pkg/utils/hash.go
Comment (LucaRocco) [inline pkg/utils/hash.go:1]: Regarding this please check [here](https://github.com/aquasecurity/tracee/issues/4868#issuecomment-3173158685) please
