### PR TITLE
Run integration test triggers in own PID

### LINKED ISSUE #2073: [BUG] Flaky integration test
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug. (Partially, other issues with this test)

Select one OR another:

- [x] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

Running the `do_a_file_write` integration test fails. When I run it on my machine there's a value mismatch because it just reads in the first event for `magic_write` and compares it to a hard coded slice of bytes. This doesn't work if another magic_write event occurs elsewhere on the system. We need to filter for the exact event properly.

## Steps to reproduce

Steps to reproduce the issue:

1. `sudo make test-integration`

### PR DESCRIPTION
**Pull request by grantseltzer**
## Initial Checklist

- [x] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

This is a change to the integration tests so that the commands which are meant to trigger events that the tests look for, are actually picked up by tracee. In order for this to happen, the events can't be the same PID as tracee. This is accomplished using syscall.ForkExec() which runs functions in a shell script.

Signed-off-by: grantseltzer <grantseltzer@gmail.com>

Fixes #2073 

## Type of change

- [x] Bug fix (non-breaking change fixing an issue, preferable).
- [ ] Quick fix (minor non-breaking change requiring no issue, use with care)
- [ ] Code refactor (code improvement and/or code removal)
- [ ] New feature (non-breaking change adding functionality).
- [ ] Breaking change (cause existing functionality not to work as expected).

## How Has This Been Tested?

`sudo make test-integration`

### CODE REVIEW

File: tests/integration/integration_test.go [hunk 1]
```diff
@@ -16,49 +17,30 @@ import (
...
+
+	_, err := forkAndExecFunction(doMagicWrite)
+	require.NoError(t, err)
+
+	waitForTraceeOutput(t, gotOutput, time.Now(), true)
+
+	// check tracee output
+	fail := true
+	for _, evt := range *gotOutput {
+		ok := assert.ElementsMatch(t, []byte(evt.EventName), []byte("magic_write"))
```
Comment (NDStrahilevitz) [inline tests/integration/integration_test.go:31]: Why are you comparing this way and not just
```suggestion
		ok := assert.Equal(t, evt.Eventname, "magic_write")
```
Also am I reading it correct that if you find magic_write then the test fails? Shouldn't it be the opposite? If not we can also break on the `if ok` check.

File: tests/integration/integration_test.go [hunk 2]
```diff
@@ -291,3 +270,35 @@ func Test_EventFilters(t *testing.T) {
...
+const (
+	doMagicWrite = "do_magic_write"
+	doLs         = "do_ls"
+	doDockerRun  = "do_docker_run"
+)
+
+// forkAndExecFunction runs a function in `tester.sh` in it's own system process.
+// This is so Tracee running in the current pid can pick the command up.
+// It returns the output of the process and a possible error.
+func forkAndExecFunction(funcName string) ([]byte, error) {
```
Comment (NDStrahilevitz) [inline tests/integration/integration_test.go:283]: Small suggestion, we can do
`type testFunc string`
and then define the consts above as such and `funcName` as such, which would prevent passing something arbitrary here in the future by mistake.

**Review by NDStrahilevitz — APPROVED** [review]
I like this, think the testing code is also cleaner this way, would like an answer on comment 1 before giving a +1, but otherwise LGTM.

File: tests/integration/integration_test.go (hunk 1 above)
Comment (grantseltzer) [reply tests/integration/integration_test.go]: It is the opposite because fail is set to false. It is a bit backwards but it makes sense here to fail unless all criteria marks it as success.

File: tests/integration/integration_test.go (hunk 2 above)
Comment (grantseltzer) [reply tests/integration/integration_test.go]: Sounds good!

**Review by yanivagman — APPROVED** [review]
LGTM

File: tests/integration/integration_test.go (hunk 1 above)
Comment (grantseltzer) [reply tests/integration/integration_test.go]: Good point, I cleaned it up
