### PR TITLE
Fix event listing

### LINKED ISSUE #382: Listing events is broken
When using `tracee -l` to list the events, the output includes many blank lines and "other events" is empty.
This was probably caused as a result of adding support for arm64 architecture

### PR DESCRIPTION
**Pull request by yanivagman**
Fix #382

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -588,7 +588,7 @@ func printList() {
 	}
 	b.WriteString("\n\nOther Events:              Sets:\n")
 	b.WriteString("____________               ____\n\n")
-	for i := int(tracee.SysEnterEventID); i < len(tracee.EventsIDToEvent); i++ {
+	for i := int(tracee.SysEnterEventID); i < int(tracee.MaxEventID); i++ {
```
Comment (itaysk) [inline main.go:591]: is this change needed for the fix?

Comment (yanivagman) [reply main.go:591]: The length of the map is now smaller than the maximum event id.
There is a gap between the last syscall number (arch dependent) and common events (starting from 1000)

File: main.go [hunk 2]
```diff
@@ -576,7 +576,7 @@ func printList() {
 	b.WriteString("____________               ____\n\n")
 	for i := 0; i < int(tracee.SysEnterEventID); i++ {
 		event := tracee.EventsIDToEvent[int32(i)]
-		if event.Name == "reserved" {
+		if event.Name == "" {
```
[the remark this answers is not in the document]
Comment (yanivagman) [reply main.go]: We can't assume syscalls are sequential - there are unimplemented syscalls in arm, for example.
continue is good enough

**Review by itaysk — APPROVED** [review]
